apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  system: oscar-example
  type: website
  lifecycle: experimental
  owner: Application Enablement
metadata:
  name: java-maven-pipeline-example
  description: Application Enablement pipeline testing example for Java + Maven +
    Tomcat application in bcgov
  title: ONETEAM-EXAMPLE
  annotations:
    license: Apache-2.0
    composer.io.nrs.gov.bc.ca/generators: backstage,gh-maven-build,gh-oci-deploy-onprem
    playbook.io.nrs.gov.bc.ca/clientId: e985d455-b0ff-470b-8731-e004fcfac915
    playbook.io.nrs.gov.bc.ca/javaVersion: "21"
    playbook.io.nrs.gov.bc.ca/javaPattern: Tomcat
    playbook.io.nrs.gov.bc.ca/pomRoot: ./
    playbook.io.nrs.gov.bc.ca/ociArtifacts: ""
    playbook.io.nrs.gov.bc.ca/publishArtifactSuffix: dist
    playbook.io.nrs.gov.bc.ca/unitTestsPath: ""
    playbook.io.nrs.gov.bc.ca/artifactRepositoryType: GitHubPackages
    playbook.io.nrs.gov.bc.ca/toolsBuildSecrets: ARTIFACTORY_USERNAME,ARTIFACTORY_PASSWORD
    playbook.io.nrs.gov.bc.ca/toolsLocalBuildSecrets: ARTIFACTORY_USERNAME,ARTIFACTORY_PASSWORD
    playbook.io.nrs.gov.bc.ca/mavenBuildCommand: --batch-mode -Dmaven.test.skip=true -Pgithub clean package
    github.com/project-slug: bcgov/nr-appenablement-pipeline-sample
    playbook.io.nrs.gov.bc.ca/artifactRepositoryPath: https://maven.pkg.github.com/bcgov/nr-appenablement-pipeline-sample
    playbook.io.nrs.gov.bc.ca/postDeployTestsPath: ""
    playbook.io.nrs.gov.bc.ca/deployType: tomcat
    playbook.io.nrs.gov.bc.ca/artifactSrc: repo
    playbook.io.nrs.gov.bc.ca/deploymentConfigPaths: playbooks
    playbook.io.nrs.gov.bc.ca/tomcatContext: pub#java-maven-pipeline-example
    playbook.io.nrs.gov.bc.ca/useAltAppDirName: false
    playbook.io.nrs.gov.bc.ca/addLog4j2Config: false
    playbook.io.nrs.gov.bc.ca/addTomcatContext: true
    playbook.io.nrs.gov.bc.ca/createDataTmpDir: false
    playbook.io.nrs.gov.bc.ca/addWebadeConfig: false
